((nil . ((compile-command . "nix-shell env-dolly.nix --run \"ninja -C ~/workspace/dolly/Release/\"")))
 (c-mode . ((mode . c++)
            (c-basic-offset . 2)))
 (c++-mode . ((c-basic-offset . 2)))
 )
