((nil . ((default-directory . "~/workspace/dolly/")
         (compile-command . "ninja -C Release")))
 (c-mode . ((mode . c++)
            (c-basic-offset . 2)))
 (c++-mode . ((c-basic-offset . 2)))
 )
