((nil . ((projectile-project-compilation-cmd . "NAILGUN_SERVER=local:.buckd/sock ng com.facebook.buck.cli.Main build :db")))
 (c-mode . ((mode . c++)
            (c-basic-offset . 2)))
 (c++-mode . ((c-basic-offset . 2)))
 )
